### ISSUE TITLE
Machine edit function fails inconsistenly

### ISSUE THREAD

**Issue by SaeedRazavi** [CalvinKrist/ProjectBrightSun#127]
Sometimes (but not always, oddly enough) when machines are edited and "save edits" is clicked in modal, the function does not work properly. 

Sometimes the saved edits are displayed on the card but not saved in the machine properties

Sometimes the saved edits are not actually saved, nor displayed

Sometimes the textbox in the edit modal won't focus

Sometimes everything functions perfectly. The inconsistency of the bug is perplexing.
Bugs seem to arise more commonly when boxes are cloned. Name data can be viewed in the confirmation message when attempting to remove a machine.

**Comment by ION28** [comment]
That's weird. I'll take a look at some point

**Comment by CalvinKrist** [comment]
My guess is it's related to the changes I made in commit bc90e19bb49603bf3e952c689f665ddff7fd689b.  Before, the machine modals were added through the 'add_box' function which pulled parameters directly from the 'Add Machine' modal. I seperated the actual machine creation from the code that retrieved the parameters in order to support advanced features in the future as well as easily importing machines. The actual modals are now added in the 'add_machine_box' function. This function does not add the machine parameters to window.boxes: it is the responsibility of the caller to do so. It simply accepts a 'machine' object and creates a modal with those parameters.

The 'save_edits' function was not refactored to use the new 'add_machine_box' function. This should be done.

The clone functions and delete functions may have similarly not been updated, resulting in these bugs. I have not investigated this, however.

**Comment by CalvinKrist** [comment]
I would also mention that when I delete a machine modal, I can no longer clone modals. This seems to be a repeatable glitch.

**Comment by CalvinKrist** [comment]
These issues came down to a corrupted machine state. Sometimes the new functions for drawing to the screen were used, and sometimes not. Thus, mixing methods produced unpredictable results.

Now, if window.boxes changes, please call "update_machine_modals()". That's it. Always do that if the state changes and everything will be fine. *note: you really only need to call it if the state visually displayed changes . . .*

While debugging these bugs, I found three more loosely documented in issues #128, #129, and #130. These will need to be handled sometime.

Please test the fix and let me know if you find any more issues.
